[project]
name = "pypiactl"
version = "0.1.0"
description = "A wrapper for the Private Internet Access (PIA) command line interface."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
